In [ ]:
import numpy as np

N = int(input('N = '))
A = range(N*N)
A = np.reshape(A,(N,N))

a = int(input('a = '))
A[:,0:6] = 0
A[:,0] = a
A[:,4] = a
A[0,:] = a
A[4,:] = a
print(A)

N = 5
a = 6
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]
